# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

# command to install dependencies
install:
  - "pip install coveralls"

# command to run tests
script:
  coverage run --source=tinytag $(command -v nosetests)

after_success:
  coveralls
