# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

# command to install dependencies
install:
  - "pip install coveralls"
  - "pip install pytest"
  - "pip install pytest-cov"

# command to run tests
script:
  pytest --cov=tinytag --cov-branch --cov-report xml:test-results/coverage.xml --junitxml test-results/junit.xml

after_success:
  coveralls
